[project]
name = "ikoma"
version = "0.1.0"
description = "iKOMA AI Agent - Phase 1-B"
dependencies = [
    "langchain-openai",
    "langgraph",
    "chromadb",
    "python-dotenv",
    "openai",
    "pathlib",
    "uuid",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["agent*", "tools*"] 