name: Performance Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          .venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        
    - name: Install dependencies
      run: |
        pip install -e .
        pip install matplotlib  # For trend charts
        
    - name: Run benchmarks
      id: bench
      run: |
        python -m benchmarks.bench > benchmark_output.txt
        echo "has_regression=$?" >> $GITHUB_OUTPUT
        
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          benchmark_results.json
          benchmark_output.txt
          
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          try {
            const fs = require('fs');
            const output = fs.readFileSync('benchmark_output.txt', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
            console.log('✅ Benchmark results posted to PR');
          } catch (error) {
            console.log('⚠️ Could not post benchmark results to PR:', error.message);
            console.log('This is likely due to permissions. Results are still available as artifacts.');
          }
          
    - name: Fail if regression detected
      if: steps.bench.outputs.has_regression == '1'
      run: exit 1 