name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: pyproject.toml
      
      - name: Install dependencies
        run: |
          pip install -e .
          pip install ruff pytest pytest-cov mypy bandit pip-audit types-beautifulsoup4
      
      - name: Lint & Format
        run: |
          ruff check .
          ruff format --check --diff .
      
      - name: Type Check
        run: mypy agent tools --explicit-package-bases
        if: matrix.python == '3.11'
      
      - name: Test with Coverage
        run: |
          pytest tests/ -m "not dashboard" \
            --cov=agent --cov=tools \
            --cov-report=term-missing \
            --cov-fail-under=35
      
      - name: Security Check
        run: |
          bandit -r agent tools -ll
          pip-audit \
            --ignore-vuln GHSA-887c-mr87-cxwp \
            --ignore-vuln GHSA-6rvg-6v2m-4j46 \
            --ignore-vuln GHSA-fpwr-67px-3qhx \
            --ignore-vuln PYSEC-2024-227 \
            --ignore-vuln PYSEC-2024-228 \
            --ignore-vuln PYSEC-2024-229 \
            --ignore-vuln PYSEC-2025-40 \
            --ignore-vuln GHSA-q2wp-rjmx-x6x9 \
            --ignore-vuln GHSA-jjph-296x-mrcr \
            --ignore-vuln GHSA-phhr-52qp-3mj4 \
            --ignore-vuln GHSA-37mw-44qp-f5jm \
            --ignore-vuln PYSEC-2022-43012 \
            --ignore-vuln PYSEC-2025-49
        if: matrix.python == '3.11'
      
      - name: Build Package
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/
        if: matrix.python == '3.11'
