name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: pyproject.toml
      
      - name: Install dependencies
        run: |
          pip install -e .
          pip install ruff pytest pytest-cov pytest-timeout mypy bandit pip-audit types-beautifulsoup4
      
      - name: Lint & Format
        run: |
          ruff check .
          ruff format --check --diff .
      
      - name: Type Check
        run: mypy agent tools --explicit-package-bases
      
      - name: Test with Coverage
        env:
          CI: true
        timeout-minutes: 10
        run: |
          pytest tests/ \
            -m "not dashboard" \
            --ignore=tests/test_cleanup_analysis.py \
            --ignore=tests/test_persistence_vector_store.py \
            --ignore=tests/test_citation_vector_store.py \
            --ignore=tests/test_web_extraction_citation.py \
            --ignore=tests/test_citation_performance.py \
            --ignore=tests/test_tui_demo.py \
            --ignore=tests/test_metrics_dashboard.py \
            --ignore=tests/test_web_extraction.py \
            --cov=agent --cov=tools \
            --cov-report=term-missing \
            --cov-fail-under=25 \
            --tb=short \
            --maxfail=3 \
            --timeout=300
      
      - name: Security Check
        run: |
          bandit -r agent tools -ll
          pip-audit \
            --ignore-vuln GHSA-887c-mr87-cxwp \
            --ignore-vuln GHSA-6rvg-6v2m-4j46 \
            --ignore-vuln GHSA-fpwr-67px-3qhx \
            --ignore-vuln PYSEC-2024-227 \
            --ignore-vuln PYSEC-2024-228 \
            --ignore-vuln PYSEC-2024-229 \
            --ignore-vuln PYSEC-2025-40 \
            --ignore-vuln GHSA-q2wp-rjmx-x6x9 \
            --ignore-vuln GHSA-jjph-296x-mrcr \
            --ignore-vuln GHSA-phhr-52qp-3mj4 \
            --ignore-vuln GHSA-37mw-44qp-f5jm \
            --ignore-vuln PYSEC-2022-43012 \
            --ignore-vuln PYSEC-2025-49 \
            --ignore-vuln GHSA-9wx4-h78v-vm56 \
            --ignore-vuln GHSA-9hjg-9r4m-mvj7 \
            --ignore-vuln GHSA-2c2j-9gv5-cj73
      
      - name: Build Package
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/
